DB_DRIVER: "postgres"
DB_SOURCE: "postgresql://root:secret@localhost:5432/card_manage?sslmode=disable"
SERVER_ADDRESS: "0.0.0.0:8080"
JWT_SECRET: "a_very_secret_key_that_should_be_changed"
JWT_EXPIRES_IN: "24h"
